# Generated by Django 6.0.5 on 2026-05-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_communityarea_area_id_alter_communityarea_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityarea',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
