# Generated by Django 6.0.5 on 2026-05-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_communityarea_population'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='restaurantpermit',
            index=models.Index(fields=['issue_date', 'community_area_id'], name='permit_date_area_idx'),
        ),
    ]
